import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.ToString;

import java.util.Arrays;


// getters and constructors are
// automatically generated by the annotations

@Getter
@NoArgsConstructor
@ToString
@EqualsAndHashCode
public class Converter {

    public String validate(int[] binaryDigits) {
        if(binaryDigits.length != 8) {
            throw new IllegalArgumentException("Number of inputted binary digits should be 8, not " + binaryDigits.length);
        }
        Arrays.stream(binaryDigits).forEach(digit -> {
            if (digit != 0 && digit != 1) {
                throw new IllegalArgumentException("Illegal inputted binary digit " + digit + ", input should be either 1 or 0");
            }
        });
        return "OK";
    }
}
