import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;


// getters, setters and constructors are
// automatically generated by the annotations

@Getter
@Setter
@NoArgsConstructor
@ToString
@EqualsAndHashCode
public class FT {

}
