import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.ToString;


// getters and constructors are
// automatically generated by the annotations

@Getter
@NoArgsConstructor
@ToString
@EqualsAndHashCode
public class SpringArray {

    public static Spring equivalentSpring(String springExpr) {
        //TODO
      return null;
    }

    public static Spring equivalentSpring(String springExpr, Spring[] springs) {
        //TODO
        return null;
    }
}
